# Generated by Django 4.1.3 on 2022-11-01 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="name",
            field=models.CharField(default="", max_length=100),
        ),
    ]
